export enum ActionTypes {
  ADD_COFFEE_TO_CART = 'ADD_COFFEE_TO_CART',
  DELETE_COFFEE_FROM_CART = 'DELETE_COFFEE_FROM_CART',
  INCREASE_AMOUNT_ON_CART = 'INCREASE_AMOUNT_ON_CART',
  DECREASE_AMOUNT_ON_CART = 'DECREASE_AMOUNT_ON_CART',
  CLEAN_CART = 'CLEAN_CART',
  SET_ADRESS_AND_PAYMENT_METHOD = 'SET_ADRESS_AND_PAYMENT_METHOD',
}
